import Head from "next/head";
import Link from "next/link";
import Nav from "../component/nav";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>tutorial blog app</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p className={styles.webAccess}>
				<a href="#content-bottom">하위 본문으로 이동</a>
			</p>
			<header id="header" className={styles.header}>
				<Nav />
			</header>
			<main id="main" className={styles.main}>
				<section id="content-top" className={styles.section__Top}>
					<article className={styles.article__Top}>
						<Link to="/detail">
							<div>
								<h3>상위 article 입니다.</h3>
								<p>내용</p>
								<span>날짜 : 2020/06/24</span>
							</div>
						</Link>
					</article>
					<article className={styles.article__Top}>
						<div>
							<h3>상위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
					<article className={styles.article__Top}>
						<div>
							<h3>상위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
				</section>
				<section id="content-bottom" className={styles.section__Bottom}>
					<article className={styles.article__bottom}>
						<div>
							<h3>하위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
					<article className={styles.article__bottom}>
						<div>
							<h3>하위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
					<article className={styles.article__bottom}>
						<div>
							<h3>하위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
					<article className={styles.article__bottom}>
						<div>
							<h3>하위 article 입니다.</h3>
							<p>내용</p>
							<span>날짜 : 2020/06/24</span>
						</div>
					</article>
				</section>
			</main>
			<footer id="footer" className={styles.footer}>
				footer 입니다.
			</footer>
		</div>
	);
}
